# Your personal GitHub token
github_token: dfc8591d0ed9857a86ba699973b91af3e2061239
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: yii2basic

# Virtual machine IP
ip: 192.168.83.137

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024
